sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t 040772/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true 040772/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3" 
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-248749481552"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  