FROM node:16-alpine

RUN addgroup app && adduser -S -G app app
RUN mkdir /app && chown -R app:app /app
RUN chmod 777 /app -R
USER app
WORKDIR /app


COPY package.json .
RUN npm install 

COPY . .

CMD ["npm", "run", "start"]
